# Site settings
locale                   : "en-US"
title                    : "CC"
email                    : "masoncc@gmu.edu"
description              : "Mason CC"
author                   : "Mason CC"

# the subpath of your site, e.g. /blog
baseurl                  : ""
# the base hostname & protocol for your site, e.g. http://example.com
url                      : "https://competitivecyber.club"


# Social Sharing
twitter:
  username               : "masoncompcyber"
github:
  username               : "masoncompcyber"
facebook:
  username               : "masoncompcyber"
  app_id                 :
  publisher              :

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock

# Build settings
markdown: kramdown


defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      jumbotron: false
